name: ease
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pandas=1.1.5
  - py-xgboost=1.5.1
  - libxgboost=1.5.1
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - tbb=2022.0.0
  - tbb4py=2021.7.0
  - pip:
    - cycler==0.11.0
    - fonttools==4.38.0
    - imbalanced-ensemble==0.1.7
    - imbalanced-learn==0.11.0
    - ipdb==0.13.13
    - ipython==7.34.0
    - jedi==0.19.2
    - joblib==1.3.2
    - hdbscan
    - kiwisolver==1.4.5
    - lightgbm==4.6.0
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - numpy==1.21.6
    - packaging==24.0
    - parso==0.8.5
    - pillow==9.5.0
    - pyparsing==3.1.4
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.2
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - tqdm==4.67.1
    - typing-extensions==4.7.1
    - wcwidth==0.2.14